export const STARTLOADER = "STARTLOADER";
export const STOPLOADER = "STOPLOADER";
export const SETMSG = "SETMSG";
export const CLRMSG = "CLRMSG";
export const RESET_ALL_STATE = "RESET_ALL_STATE";

export const GET_PATIENT_LIST = "GET_PATIENT_LIST";
export const GET_SYMPTOM_LIST = "GET_SYMPTOM_LIST";
export const GET_DISEASE_LIST = "GET_DISEASE_LIST";

export const DOCTOR_REGISTERED = "DOCTOR_REGISTERED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";

export const DOCTOR_PROFILE_UPDATED = "DOCTOR_PROFILE_UPDATED";


export const GET_DIAGNOSIS_LIST = "GET_DIAGNOSIS_LIST";